spring:
  datasource:
    url: jdbc:h2:mem:pdf-viewer
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false

logging:
  level:
    com.pdfviewer: INFO
  file:
    name: logs/pdf-viewer.log

